### ISSUE TITLE
Running make model command throws IsADirectoryError

### ISSUE THREAD

**Issue by vinhtq115** [shuichiro-makigaki/exmachina#2]
I'm trying to run `python exmachina.py generate-model /usr/lib/modeller9.25/bin/mod9.25_x86_64-intel8 tests/data/d1qg3a1.mtx tests/data/d1va9a1.mtx A results/alignments.npy tests/data/` based on your notebook example but it always throws this error:
```
Traceback (most recent call last):
  File "exmachina.py", line 184, in <module>
    main()
  File "/home/vinhtq115/anaconda3/envs/tinsinh/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/vinhtq115/anaconda3/envs/tinsinh/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/vinhtq115/anaconda3/envs/tinsinh/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vinhtq115/anaconda3/envs/tinsinh/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vinhtq115/anaconda3/envs/tinsinh/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "exmachina.py", line 116, in generate_model
    Path(query), Path(template), chain, Path(alignment), Path(atom_dir), Path(out_dir))
  File "/media/vinhtq115/DATA/tinsinh/exmachina/machina/generate_models.py", line 67, in generate_protein_model
    tseq = replace_missing_residues(best[1], template_id, chain, template_file.as_posix())
  File "/media/vinhtq115/DATA/tinsinh/exmachina/machina/generate_models.py", line 20, in replace_missing_residues
    template_pdb = [str(_.seq) for _ in SeqIO.parse(pdb, 'pdb-atom') if _.id == f'{template_id}:{chain}']
  File "/media/vinhtq115/DATA/tinsinh/exmachina/machina/generate_models.py", line 20, in <listcomp>
    template_pdb = [str(_.seq) for _ in SeqIO.parse(pdb, 'pdb-atom') if _.id == f'{template_id}:{chain}']
  File "/home/vinhtq115/anaconda3/envs/tinsinh/lib/python3.7/site-packages/Bio/SeqIO/PdbIO.py", line 299, in PdbAtomIterator
    structure = PDBParser().get_structure(None, source)
  File "/home/vinhtq115/anaconda3/envs/tinsinh/lib/python3.7/site-packages/Bio/PDB/PDBParser.py", line 96, in get_structure
    with as_handle(file) as handle:
  File "/home/vinhtq115/anaconda3/envs/tinsinh/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/vinhtq115/anaconda3/envs/tinsinh/lib/python3.7/site-packages/Bio/File.py", line 71, in as_handle
    with open(handleish, mode, **kwargs) as fp:
IsADirectoryError: [Errno 21] Is a directory: 'tests/data'
```
How can I fix it?

**Comment by shuichiro-makigaki** [comment]
I'm sorry for the late response and inconvenience.

The `generate-model` had not worked as you said, and I fixed it at the current master branch.

Example:

```
python3 exmachina.py generate-model /opt/modeller-9.20/bin/modpy.sh tests/data/d1qg3a1.mtx tests/data/d1va9a1.mtx A results/alignments.npy tests/data
```
